function buildRichTestHtml() {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>
html,body{margin:0;height:430px;overflow:hidden;font-family:Arial,sans-serif;background:#101820;color:#fff}.app{height:430px;display:grid;place-items:center;text-align:center;padding:12px}h2{margin:0 0 8px;font-size:22px}.ok{margin:0 0 12px;font-size:15px}#counter{margin:0 0 8px;font-size:32px;font-weight:700}#canvasTest{display:block;width:240px;height:160px;margin:0 auto 10px;border:1px solid #4c6a7a;border-radius:8px;background:#172a35}.buttons{display:flex;gap:10px;justify-content:center}button{min-width:90px;min-height:42px;border:0;border-radius:6px;background:#ffcb05;color:#1f2937;font-size:17px;font-weight:700}button:active{background:#f2b807;transform:translateY(1px)}
</style></head><body><div class="app"><div><h2>Rich HTML Test</h2><p class="ok">HTML funcionando!</p><p id="counter">0</p><canvas id="canvasTest" width="240" height="160" aria-label="Teste de Canvas"></canvas><div class="buttons"><button type="button" onclick="add()">+1</button><button type="button" onclick="resetCounter()">Reset</button><button type="button" id="animationButton">Pausar</button></div></div></div><script>
let value=0;const counter=document.getElementById('counter');const canvas=document.getElementById('canvasTest');const context=canvas.getContext('2d');const animationButton=document.getElementById('animationButton');let animationRunning=true;let squareX=0;let direction=1;function render(){counter.textContent=String(value)}function add(){value+=1;render()}function resetCounter(){value=0;render()}function drawCanvas(){context.fillStyle='#172a35';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#2b4655';for(let x=0;x<canvas.width;x+=24){context.fillRect(x,0,1,canvas.height)}context.fillStyle='#ffcb05';context.fillRect(squareX,64,28,28);context.fillStyle='#101820';context.fillRect(squareX+18,72,4,4)}function animateCanvas(){if(animationRunning){squareX+=direction*1.5;if(squareX+28>=canvas.width||squareX<=0){direction*=-1;squareX=Math.max(0,Math.min(canvas.width-28,squareX))}drawCanvas()}requestAnimationFrame(animateCanvas)}animationButton.addEventListener('click',function(){animationRunning=!animationRunning;animationButton.textContent=animationRunning?'Pausar':'Iniciar';if(!animationRunning)drawCanvas()});render();drawCanvas();requestAnimationFrame(animateCanvas);
</script></body></html>`;
}

export { buildRichTestHtml };
